/**
 * Verification report generation (Markdown and JSON).
 */
import type { VerificationResult } from "./types";
import type { MockAddress } from "@/lib/generator/generate";

export interface ReportData {
  result: VerificationResult;
  addresses: MockAddress[];
}

export function generateMarkdownReport(data: ReportData): string {
  const { result } = data;
  const lines: string[] = [];

  lines.push("# Verification Report");
  lines.push("");
  lines.push(`**Generated:** ${result.timestamp}`);
  lines.push(`**Sample size:** ${result.count} addresses`);
  if (result.seed !== null) {
    lines.push(`**Seed:** ${result.seed}`);
  }
  lines.push("");

  // Summary
  const allPassed =
    result.totalFailedRows === 0 && result.setChecks.every((c) => c.passed);
  lines.push("## Summary");
  lines.push("");
  if (allPassed) {
    lines.push("✅ **All checks passed.**");
  } else {
    lines.push(
      `⚠️ **${result.totalFailedRows} unique records failed at least one check.**`,
    );
    const failedSetChecks = result.setChecks.filter((c) => !c.passed);
    if (failedSetChecks.length > 0) {
      lines.push(`⚠️ **${failedSetChecks.length} set-level checks failed.**`);
    }
  }
  lines.push("");

  // Record-level checks
  lines.push("## Record-Level Checks");
  lines.push("");
  for (const check of result.recordChecks) {
    const icon = check.failed === 0 ? "✅" : "⚠️";
    lines.push(`### ${icon} ${check.label}`);
    lines.push("");
    lines.push(`- **Passed:** ${check.passed}`);
    lines.push(`- **Failed:** ${check.failed}`);
    if (check.failed > 0 && check.failedIds.length <= 20) {
      lines.push(`- **Failed IDs:** ${check.failedIds.join(", ")}`);
    } else if (check.failed > 20) {
      lines.push(
        `- **Failed IDs:** ${check.failedIds.slice(0, 20).join(", ")} … (${check.failed - 20} more)`,
      );
    }
    lines.push("");
  }

  // Set-level checks
  lines.push("## Set-Level Checks");
  lines.push("");
  for (const check of result.setChecks) {
    const icon = check.passed ? "✅" : "⚠️";
    lines.push(`### ${icon} ${check.label}`);
    lines.push("");
    lines.push(check.message);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by SA Mock Address Lab verification*");
  lines.push("");

  return lines.join("\n");
}

export function generateJSONReport(data: ReportData): string {
  return (
    JSON.stringify(
      {
        timestamp: data.result.timestamp,
        seed: data.result.seed,
        count: data.result.count,
        summary: {
          totalFailedRows: data.result.totalFailedRows,
          allChecksPassed:
            data.result.totalFailedRows === 0 &&
            data.result.setChecks.every((c) => c.passed),
        },
        recordChecks: data.result.recordChecks,
        setChecks: data.result.setChecks,
      },
      null,
      2,
    ) + "\n"
  );
}
